#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SignIn.UI.Android.Resource", IsApplication=true)]

namespace SignIn.UI.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			SignIn.Core.Resource.String.library_name = SignIn.UI.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int checkBoxAttended = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int listView1 = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int listViewAttendees = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int lstItemEvent = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int tableEventDetail = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int tableRow1 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int tableRow2 = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow3 = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int textAttendeeType = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int textDate = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int textDateLabel = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int textEventTitle = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int textFullName = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int textLSC = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int textRep = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int textRepLabel = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int textSpeaker = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int textSpeakerLabel = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int textVenue = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int textVenueLabel = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int txtDescription = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int txtLSC = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventPerson = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventPersonItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int CHK_ATTENDEEID = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
